insert into states (name, alias, country_id) values
('Вінницька область', 'vinnytska-oblast', 1),
('Волинська область', 'volynska-oblast', 1),
('Дніпропетровська область', 'dnipropetrovska-oblast', 1),
('Донецька область', 'donetska-oblast', 1),
('Житомирська область', 'zhytomyrska-oblast', 1),
('Закарпатська область', 'zakarpatska-oblast', 1),
('Запорізька область', 'zaporizka-oblast', 1),
('Івано-Франківська область', 'ivano-frankivska-oblast', 1),
('Київська область', 'kyivska-oblast', 1),
('Кіровоградська область', 'kirovohradska-oblast', 1),
('Луганська область', 'luhanska-oblast', 1),
('Львівська область', 'lvivska-oblast', 1),
('Миколаївська область', 'mykolaivska-oblast', 1),
('Одеська область', 'odeska-oblast', 1),
('Полтавська область', 'poltavska-oblast', 1),
('Рівненська область', 'rivnenska-oblast', 1),
('Сумська область', 'sumska-oblast', 1),
('Тернопільська область', 'ternopilska-oblast', 1),
('Харківська область', 'kharkivska-oblast', 1),
('Херсонська область', 'khersonska-oblast', 1),
('Хмельницька область', 'khmelnytska-oblast', 1),
('Черкаська область', 'cherkaska-oblast', 1),
('Чернівецька область', 'chernivetska-oblast', 1),
('Чернігівська область', 'chernihivska-oblast', 1),
('Автономна республіка Крим', 'avtonomna-respublika-krym', 1);